apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: owncloud1
status:
  loadBalancer:
    ingress:
      - ip: 192.168.17.10
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - owncloud.doianov.me
      secretName: owncloud
  rules:
    - host: owncloud.doianov.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: owncloud1
                port:
                  number: 80

