{{- if .Values.owncloud.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      containers:
        - name: owncloud
          image: {{ index .Values.template.containers 0 | default "" }}
         #image: {{ .Values.template.containers[0].image }}
          ports:
            - containerPort: {{ .Values.template.containers[0].ports[0].containerPort }}
          env: {{ toYaml .Values.template.containers[0].env | nindent 12 }}
          volumeMounts: {{ toYaml .Values.template.containers[0].volumeMounts | nindent 12 }}
      volumes: 
{{ toYaml .Values.template.volumes | nindent 8 }}
{{- end -}}
