{{- if .Values.owncloud.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      containers:
        - name: owncloud
          image: {{ .Values.template.containers.image }}
          ports:
            - containerPort: {{ .Values.template.containers.ports.containerPort }}
          env: {{ toYaml .Values.template.containers.env | nindent 12 }}
          volumeMounts: {{ toYaml .Values.template.containers.volumeMounts | nindent 12 }}
      volumes: 
{{ toYaml .Values.template.volumes | nindent 8 }}
{{- end -}}
