{{- if .Values.owncloud.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      containers:
      - name: owncloud
        image: docker.io/owncloud/server:10.6
        ports:
        - containerPort: 8080
        env:
        - name: OWNCLOUD_DOMAIN
          value: owncloud.example.com
        - name: OWNCLOUD_ADMIN_USERNAME
          value: admin
        - name: OWNCLOUD_ADMIN_PASSWORD
          value: adminpassword
        - name: MARIADB_HOST
          value: postgresql
        - name: MARIADB_PORT_NUMBER
          value: "5432"
        - name: OWNCLOUD_DATABASE_NAME
          value: owncloud
        - name: OWNCLOUD_DATABASE_USER
          value: owncloud
        - name: OWNCLOUD_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-password
        - name: OWNCLOUD_REDIS_ENABLED
          value: "true"
        - name: OWNCLOUD_REDIS_HOST
          value: redis
        volumeMounts:
        - name: owncloud-data
          mountPath: /mnt/data
      volumes:
      - name: owncloud-data
        persistentVolumeClaim:
          claimName: owncloud-data
{{- end -}}
