{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-data
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end -}}
