{{- if .Values.serviceaccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceaccount.name }}"
  labels:
    {{- with .Values.serviceaccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
